New option prefix for match-document-filename rule
B2o5T/graphql-eslint pull request #1141
Opened 2022-08-18 07:53 UTC by TuvalSimha

Closes #1139

2022-08-18 08:39 UTC, dotansimha commented on packages/plugin/tests/match-document-filename.spec.ts
> +    {
can you add tests for valid + invalid with both prefix and suffix?

2022-08-18 08:39 UTC, dotansimha commented on packages/plugin/tests/match-document-filename.spec.ts
> +    {
Also maybe test more things like fragment/query/subscription?

2022-08-18 08:40 UTC, dotansimha reviewed
- [ ] add changeset
- [x] add missing tests
- [x] make sure CI passes
- [ ] test in another project (alpha release)

2022-08-21 17:16 UTC, dotansimha requested changes

2022-08-21 17:16 UTC, dotansimha commented on .changeset/light-lizards-know.md
> +'@graphql-eslint/eslint-plugin': major
change to `minor`. @TuvalSimha

2022-08-22 14:36 UTC, TuvalSimha commented on .changeset/light-lizards-know.md
> +'@graphql-eslint/eslint-plugin': major
Done

2022-08-23 06:59 UTC, dotansimha approved these changes

2022-12-20 17:21 UTC, B2o5T approved these changes

2022-12-20 17:21 UTC, merged